### ISSUE TITLE
Not all devices porting over

### ISSUE THREAD

**Issue by TheGermanUSA** [DaveGut/Test-Code#12]
I have random devices which work fine and are being listed in Kasa app, that don't get pulled over into Hubitat. More than happy to help if you can get me some debug "how to".

**Comment by DaveGut** [comment]
Make sure you have the appropriate drivers installed for each device (there are 8 drivers).  Also, this thread is deprecated.  Code is not current.  Current is:  https://github.com/DaveGut/HubitatActive/tree/master/KasaDevices
