### ISSUE TITLE
Current working status

### ISSUE THREAD

**Issue by jbbarnes77** [DaveGut/Test-Code#13]
I see the project has been changed to deprecated. Has it been replaced by another project, is it just in a currently unmaintained but working state, or has it been abandoned because some change with Hubitat/TP-Link  has made it unusable?

A short comment on the current known state would help others with large investments in TP-Link Kasa devices know whether to proceed with a migration to Hubitat.

Thanks.

**Comment by mbardea** [comment]
I came here to say the same thing: the readme on the front page is quite confusing. It would be helpful to mention alternatives, if any, or just state that the code is still working, but not  maintained.

**Comment by DaveGut** [comment]
This repository is not longer maintained and issues are no longer addressed.  I have updated the links on the Hubitat thread.
