### ISSUE TITLE
unable to turn off infoLog in TP-Link Engr Mon Plug

### ISSUE THREAD

**Issue by rummyr** [DaveGut/Test-Code#3]
Version "4.1.01"
Line 69  -- 	
````groovy
def updated() {
        ...
	if (!infoLog || infoLog == true) {
		device.updateSetting("infoLog", [type:"bool", value: true])
	} else ...
````
My groovy is very poor, but for a false value doesn't this evaluate to !false aka "true" which means it turns on infoLog even if you turn it off in preferences?

**Comment by DaveGut** [comment]
No.  It means that if the preference has not been set OR the preference is set to true, then infolog is turned on.

**Comment by DaveGut** [comment]
closed.  Lack of further data.
