### ISSUE TITLE
TP-Link Engr Mon Plug: errors thrown from energyThisMonthResponse()

### ISSUE THREAD

**Issue by rummyr** [DaveGut/Test-Code#4]
TP-Link Engr Mon Plug version "4.1.01"
I think line 204 in energyThisMonthResponse() is throwing errors in my log
````groovy
    def monthList = cmdResponse["smartlife.iot.common.emeter"]["get_monthstat"].month_list
````
should it be something like:
````groovy
    def monthList = cmdResponse["emeter"]["get_monthstat"].month_list
````

PS.
   Thanks for all the work you have done so far getting TPLink plugs into Hubitat!

**Comment by DaveGut** [comment]
What is the error being thrown???  I need the log information.

**Comment by DaveGut** [comment]
Closing due to lack of data.
