### ISSUE TITLE
Polling model not ideal

### ISSUE THREAD

**Issue by wbierman** [DaveGut/Test-Code#5]
Hello.  Firstly let me say that I appreciate the time you've taken to create, document, and publish this work.  I have no experience with development related to home automation, but it seems like this code operates on a polling model to drive events called "rules".

What I have done is installed an HS200 switch in my backyard shed to control the flood light, and another HS200 switch on my house which functions solely to control the shed switch -- no fixture or anything else is wired into it. I have a rule setup to sync state between the two switches.  The end result is what I want: a second switch for my shed light.

However because the hubitat is polling at the devices at 60 second intervals, there is a very noticeable delay between the activation by me of one switch and the corresponding automatic activation of the other.

I assume that since it is the only option available, that there is no way to tell the HS200 to report to the hubitat when it is toggled, allowing the rules to run on an event-based system rather than a polling-based one.  Is this correct?  And what are the implications of lowering the polling frequency to minimize the delay?

I sort of feel like I might be accomplishing my goal with a round-about way.  Is there a better solution that what I have done?

**Comment by DaveGut** [comment]
You are correct in the automatic event response sent by the bulb.  
Polling can be increased by a special algorithm.  Implications is a increase in the hub processing.  Depending on how many devices you want to fast poll and the total number of devices, impact will vary.

I will write a plug/switch driver for you with rapid polling as an option - if you will promise to provide feedback after using a few months.  It will provide 5 second polling of SELECTED devices.  Instructions to follow.

**Comment by DaveGut** [comment]
I finished the special polling version.  You can create a new driver or replace the existing.  Go to the drivers page and open the current (or new) driver window.  Select import and input the below:
"https://github.com/DaveGut/Hubitat-TP-Link-Integration/blob/master/Special/SpecTPLinkPlug-Switch.groovy"
Save.
Go to Preferences on the Devices Page and select "Enable special fast polling (Not Recommended)"
Save preferences.
Note:  By default, fast polling is disabled.  You will have to enable for each device.

To restore previous version of driver, open driver in Hubitat.  Select Import and the link below:
"https://github.com/DaveGut/Hubitat-TP-Link-Integration/blob/master/Device%20Drivers/TP-Link%20Plug-Switch%20(Hubitat).groovy"

Again, use for a while and please comment.  May add for entire community.

**Comment by wbierman** [comment]
Just wanted to follow up here.  I have been travelling until yesterday, but have updated the driver and will experiment with this.  I assume the primary concern here is that the additional CPU demand on the Hubitat.  Is that right?  Is there some way that I can gather performance data before/after enabling fast polling to give you a comparison?

**Comment by DaveGut** [comment]
No way to gather performance data.  Just see if it is working OK and the hub is not brought to it’s knees.  You will need to run for several weeks w/o hang-up.  Sometime it is just resources being grabbed and not properly released when done.

Dave

**Comment by wbierman** [comment]
Okay, thank you.  This is basically all I am using this hub for, but I may add more to it in the future.  I have done an initial testing and can confirm that the system does respond within five seconds.

I'll plan to post back here after a few weeks.

**Comment by DaveGut** [comment]
FYI, here is an API document I wrote for the TP-Link Bulbs.  This was based on my research and experimentation using node.js scripts and debugging the actual code from TP-Link.

[TP-LInk Bulb API.pdf](https://github.com/DaveGut/Hubitat-TP-Link-Integration/files/3369749/TP-LInk.Bulb.API.pdf)

**Comment by DaveGut** [comment]
Closing as solution accepted.
