### ISSUE TITLE
Import URL is wrong for TP-LinkPlug-Switch(Hubitat)

### ISSUE THREAD

**Issue by bdwilson** [DaveGut/Test-Code#7]
It should be: https://raw.githubusercontent.com/DaveGut/Hubitat-TP-Link-Integration/master/DeviceDrivers/TP-LinkPlug-Switch(Hubitat).groovy

**Comment by DaveGut** [comment]
It will be corrected in a future release.

**Comment by DaveGut** [comment]
Fixed in latest update
