### ISSUE TITLE
Ip Scan does not take subnet into account

### ISSUE THREAD

**Issue by btsteve** [DaveGut/Test-Code#9]
It looks like the ip scan does not take into account is you have a network larger than a /24. 
If your network is a /23 then you miss half of the ips.

**Comment by DaveGut** [comment]
Suggestions on fixing?  Now I search manually (since Hubitat does not support UDP discovery). 

As an alternative, you can do a manual installation (supported by all of the drivers).  Simply install the driver, create a device using the driver, and enter the IP address.

**Comment by DaveGut** [comment]
I can not update the code.  The integration supports subnet using the manual installation capability.
